[package]
name = "rse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tl = "0.7.7"
serde_json = "1.0.105"
serde = "1.0.188"
serde_derive = "1.0.188"
rust-stemmers = "1.2.0"
tiny_http = "0.12.0"